version: '3.8'

services:
  metalhead-pos:
    image: metalhead-pos
    container_name: metalhead-pos
    env_file:
      - ./.env.local
    restart: always
    networks:
      proxy:
        aliases:
          - mhpos
          - metalhead-pos

networks:
  proxy:
    external:
      name: proxy