services:
  metalhead-pos:
    build:
      context: ./
      args:
        - PUBLIC_POS_URL=${PUBLIC_POS_URL:-}
    restart: unless-stopped
    volumes:
      - pb_data:/pb/pb_data

volumes:
  pb_data:
